packages:
  '@rolla-frontend/*':
   access: ci vercel vonoro giorgio voidberg1 cosmos-redshift
   publish: ci voidberg1
   unpublish: voidberg1
   proxy: npmjs
  '@rolla-core/*':
   access: ci vercel vmendiolalau giorgio quantizations andre voidberg1 vonoro cosmos-redshift
   publish: ci voidberg1 vonoro
   unpublish: not-real-acc
   proxy: npmjs
   access: ci vercel vmendiolalau voidberg1 giorgio quantizations andre
   publish: ci andre
   unpublish: not-real-acc
   proxy: npmjs
  '@rolla-experimental/*':
   access: ci vercel vmendiolalau giorgio quantizations andre voidberg1 vonoro cosmos-redshift
   publish: ci vercel quantizations andre voidberg1 vonoro cosmos-redshift
   unpublish: ci vercel quantizations andre voidberg1 vonoro cosmos-redshift
   proxy: npmjs
  '@rolla-contracts/*':
   access: ci vercel vmendiolalau giorgio quantizations andre voidberg1 vonoro cosmos-redshift
   publish: ci quantizations andre
   unpublish: ci quantizations andre
   proxy: npmjs
  '@*/*':
    # scoped packages
    access: ci vercel giorgio veronica quantizations andre voidberg1 vonoro cosmos-redshift
    publish: ci vercel
    unpublish:
    proxy: npmjs
  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: ci vercel giorgio quantizations andre voidberg1 vonoro cosmos-redshift
    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: not-real-acc
    unpublish: not-real-acc
    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs
# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
# log settings
logs: { type: stdout, format: pretty, level: trace }
experiments:
#  # support for npm token command
  token: true
#  bytesin_off: false
#  # enable tarball URL redirect for hosting tarball with a different server, the tarball_url_redirect can be a template string
#  tarball_url_redirect: 'https://mycdn.com/verdaccio/${packageName}/${filename}'
#  # the tarball_url_redirect can be a function, takes packageName and filename and returns the url, when working with a js configuration file
#  tarball_url_redirect(packageName, filename) {
#    const signedUrl = // generate a signed url
#    return signedUrl;
#  }
# This affect the web and api (not developed yet)
#i18n:
#web: en-US
https:
    key: /verdaccio/conf/docker-nginx.key
    cert: /verdaccio/conf/docker-nginx.crt
    ca: /verdaccio/conf/docker-ca.crt
listen: 127.0.0.1:4873
#